#!/usr/bin/env ruby

require "fileutils"

def main
  filename = "template"

  file_content = File.read("./views/#{filename}.liquid")

  FileUtils.mkdir_p("dist")
  File.write("dist/#{File.basename("#{filename}.html")}", file_content)
end

main
